In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
website_pageviews = pd.read_csv(r"C:\Users\compu\Desktop\Mission Analysis\1.Funnel Analysis\2.Maven Fuzzy Factory Funnel analysis\website_pageviews.csv")
website_sessions = pd.read_csv(r"C:\Users\compu\Desktop\Mission Analysis\1.Funnel Analysis\2.Maven Fuzzy Factory Funnel analysis\website_sessions.csv")
orders = pd.read_csv(r"C:\Users\compu\Desktop\Mission Analysis\1.Funnel Analysis\2.Maven Fuzzy Factory Funnel analysis\orders.csv")

In [5]:
website_pageviews.head(3)

   website_pageview_id           created_at  website_session_id pageview_url
0                    1  2012-03-19 08:04:16                   1        /home
1                    2  2012-03-19 08:16:49                   2        /home
2                    3  2012-03-19 08:26:55                   3        /home

In [6]:
website_sessions.head(3)

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:16,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 08:16:49,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:55,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com

In [10]:
orders.head(3)

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,20,20,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,104,104,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,147,147,1,1,49.99,19.49

In [22]:
website_pageviews.head(3)

   website_pageview_id          created_at  website_session_id pageview_url
0                    1 2012-03-19 08:04:16                   1        /home
1                    2 2012-03-19 08:16:49                   2        /home
2                    3 2012-03-19 08:26:55                   3        /home

In [16]:
website_pageviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1188124 entries, 0 to 1188123
Data columns (total 4 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   website_pageview_id  1188124 non-null  int64
 1   created_at           1188124 non-null  datetime64[ns]
 2   website_session_id   1188124 non-null  int64
 3   pageview_url         1188124 non-null  object
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 36.3+ MB

In [15]:
website_pageviews['created_at'] = pd.to_datetime(website_pageviews['created_at'])

In [36]:
website_pageviews['pageview_url'].value_counts()

pageview_url
/products                      261231
/the-original-mr-fuzzy         162525
/home                          137576
/lander-2                      131170
/cart                           94953
/lander-3                       79000
/lander-5                       68166
/shipping                       64484
/billing-2                      48441
/lander-1                       47574
/thank-you-for-your-order       32313
/the-forever-love-bear          26033
/the-birthday-sugar-panda       19046
/lander-4                        9385
/billing                         3617
/the-hudson-river-mini-bear      2610
Name: count, dtype: int64

In [26]:
website_sessions.head(3)

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:16,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 08:16:49,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:55,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com

In [19]:
website_sessions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472871 entries, 0 to 472870
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   website_session_id  472871 non-null  int64
 1   created_at          472871 non-null  datetime64[ns]
 2   user_id             472871 non-null  int64
 3   is_repeat_session   472871 non-null  int64
 4   utm_source          389543 non-null  object
 5   utm_campaign        389543 non-null  object
 6   utm_content         389543 non-null  object
 7   device_type         472871 non-null  object
 8   http_referer        432954 non-null  object
dtypes: datetime64[ns](1), int64(3), object(5)
memory usage: 32.5+ MB

In [18]:
website_sessions['created_at'] = pd.to_datetime(website_sessions['created_at'])

In [30]:
website_sessions['device_type'].value_counts()

device_type
desktop    327027
mobile     145844
Name: count, dtype: int64

In [32]:
website_sessions['utm_source'].value_counts()

utm_source
gsearch       316035
bsearch        62823
socialbook     10685
Name: count, dtype: int64

In [33]:
website_sessions['utm_campaign'].value_counts()

utm_campaign
nonbrand            337615
brand                41243
desktop_targeted      5590
pilot                 5095
Name: count, dtype: int64

In [34]:
website_sessions['utm_content'].value_counts()

utm_content
g_ad_1         282706
b_ad_1          54909
g_ad_2          33329
b_ad_2           7914
social_ad_2      5590
social_ad_1      5095
Name: count, dtype: int64

In [35]:
website_sessions['http_referer'].value_counts()

http_referer
https://www.gsearch.com       351237
https://www.bsearch.com        71032
https://www.socialbook.com     10685
Name: count, dtype: int64

In [20]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32313 entries, 0 to 32312
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            32313 non-null  int64
 1   created_at          32313 non-null  object
 2   website_session_id  32313 non-null  int64
 3   user_id             32313 non-null  int64
 4   primary_product_id  32313 non-null  int64
 5   items_purchased     32313 non-null  int64
 6   price_usd           32313 non-null  float64
 7   cogs_usd            32313 non-null  float64
dtypes: float64(2), int64(5), object(1)
memory usage: 2.0+ MB

In [21]:
orders['created_at'] = pd.to_datetime(orders['created_at'])

In [37]:
import pandas as pd
from sqlalchemy import create_engine

username = "root"
password = "root9290jaya"
host = "localhost"
port = 3306
database = "fuzzy_factory"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

tables = {
    "website_pageviews": website_pageviews,
    "website_sessions": website_sessions,
    "orders": orders
}

for table_name, df in tables.items():
    df.to_sql(
        name=table_name,
        con=engine,
        if_exists="replace",
        index=False
    )
    print(f"{table_name} uploaded successfully!")

website_pageviews uploaded successfully!
website_sessions uploaded successfully!
orders uploaded successfully!